### ISSUE TITLE
Shifter doesn't work

### ISSUE THREAD

**Issue by Gavin-Perry** [danny270793/ArduinoShiftRegister#1]
There are lots of shifter libraries out there but I wanted something really simple (only need one bit set at a time) so I chose yours. I'm running on a RasPi Pico using IDE 2.3.2 with Earle Philhower's Board Manager
The example program doesn't work. I expanded it with some Serial.print statements to find the problem.
As soon as shifter.digitalwrite(bit,state) is called the program halts.
I've attached the source I used. Comment out the shifter lines (//1) and it runs (doing nothing useful) with those line it halts before the first loop finishes.
.ino file renamed to .txt to upload, 2 UF2 files (with and without the shifter running) in the zip file
[shift595digitalwrite.ino.txt](https://github.com/danny270793/ArduinoShiftRegister/files/15450427/shift595digitalwrite.ino.txt)
[shift595digitalwrite.zip](https://github.com/danny270793/ArduinoShiftRegister/files/15450448/shift595digitalwrite.zip)

**Comment by danny270793** [comment]
Hello

Please, can you share me the error you have (the full output of the arduino ide)
![WhatsApp Image 2024-05-27 at 10 13 52](https://github.com/danny270793/ArduinoShiftRegister/assets/7507703/c73d01e2-7ff2-4f21-8e2d-ecbbb25fc4a8)

And how to configure your board in my environment to test what is happening
![WhatsApp Image 2024-05-27 at 10 14 21](https://github.com/danny270793/ArduinoShiftRegister/assets/7507703/78c38f34-c772-43ce-bec6-06125adf12d4)

**Comment by Gavin-Perry** [comment]
Do you have a Pico? I gave you the source code and the compiled images that you can run. Do you get the same behavior?

Sent via the Samsung Galaxy S22 5G, an AT&T 5G smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by danny270793** [comment]
Hello

No, I dont have one :c
I'm trying to setup my environment as your to check why it fails (IDE, boards, etc), can you share how you setup you environment?

When I compile the library it works (for adruino UNO), may be is some invalid keyword with your board
Can you also share me the link of the documentation of your board?

**Comment by Gavin-Perry** [comment]
There is no problem compiling. If you don't have a PICO to try it on you won't see the problem. Program runs until shifter.digitalWrite() is called then hangs.
(I may have the capitalization wrong here, but it is correct in the program.)

Do you have any (assembler) code that is AVR or hardware specific?
Removing the 2 calls to the shifter.... (//1 in the code) and the program runs fine.
I tried changing pins but that isn't the problem. ShiftRegister74HC595 works fine so I can use that instead if you don't have resources to fix it.
Gavin

**Comment by danny270793** [comment]
Hello

So it compiles and generates a "binary" that you uploads to your shield and then fails, with the `Serial.println` you found that fails at `shifter.digitalWrite()` right? there is any logs of the execution?

The library depends on `#include "Arduino.h"` which may is not available in you microcontroller
It just fills and array with the data
![image](https://github.com/danny270793/ArduinoShiftRegister/assets/7507703/4a5ad620-e9f8-4b56-a232-7a6af7d17d19)
And then writes data out
![image](https://github.com/danny270793/ArduinoShiftRegister/assets/7507703/b9cb8327-69b4-4b7c-b027-28d5f4e748e3)
Maybe `shiftOut` because is an arduino specific code

**Comment by Gavin-Perry** [comment]
Sorry not to get back to you. Turns out I had crossed wires to my second chip! All works fine now. Thanks!

**Comment by svcsmupesynapse** [comment]
Nice to hear that, let me know any other questions do you have :)

**Comment by danny270793** [comment]
Nice to hear that, let me know any other questions do you have :)
